"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";
import { weddingInfo } from "@/lib/weddingInfo";
import { basePath } from "@/lib/basePath";

const SWIPE_THRESHOLD = 50;

// Resized WebP variants generated by scripts/optimize-images.mjs.
function imageUrl(file: string, variant: "thumb" | "full") {
  return `${basePath}/gallery/${variant}/${file.replace(/\.[^.]+$/, "")}.webp`;
}

export default function Gallery() {
  const photos = weddingInfo.gallery;
  const count = photos.length;

  const [selected, setSelected] = useState<number | null>(null);
  const [dragX, setDragX] = useState(0);
  const [dragging, setDragging] = useState(false);
  const [shift, setShift] = useState<-1 | 0 | 1>(0);
  const [instant, setInstant] = useState(false);
  const touchStartX = useRef<number | null>(null);

  const wrap = useCallback((i: number) => (i + count) % count, [count]);
  const close = useCallback(() => setSelected(null), []);
  const go = useCallback(
    (dir: -1 | 1) => {
      if (count > 1) setShift((s) => (s === 0 ? dir : s));
    },
    [count]
  );

  useEffect(() => {
    if (selected === null) return;

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
      if (e.key === "ArrowLeft") go(-1);
      if (e.key === "ArrowRight") go(1);
    };
    document.addEventListener("keydown", onKeyDown);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      document.body.style.overflow = "";
    };
  }, [selected, close, go]);

  // After snapping the track back to center without animation, re-enable transitions
  // only once that position has been painted.
  useEffect(() => {
    if (!instant) return;
    const id = requestAnimationFrame(() =>
      requestAnimationFrame(() => setInstant(false))
    );
    return () => cancelAnimationFrame(id);
  }, [instant]);

  const onTransitionEnd = (e: React.TransitionEvent<HTMLDivElement>) => {
    if (e.target !== e.currentTarget || shift === 0) return;
    setInstant(true);
    setSelected((i) => (i === null ? null : wrap(i + shift)));
    setShift(0);
  };

  const onTouchStart = (e: React.TouchEvent) => {
    if (count < 2 || shift !== 0) return;
    touchStartX.current = e.touches[0].clientX;
    setDragging(true);
  };

  const onTouchMove = (e: React.TouchEvent) => {
    if (touchStartX.current === null) return;
    setDragX(e.touches[0].clientX - touchStartX.current);
  };

  const onTouchEnd = () => {
    if (touchStartX.current === null) return;
    if (dragX <= -SWIPE_THRESHOLD) go(1);
    else if (dragX >= SWIPE_THRESHOLD) go(-1);
    touchStartX.current = null;
    setDragging(false);
    setDragX(0);
  };

  const slides =
    selected === null ? [] : count > 1 ? [wrap(selected - 1), selected, wrap(selected + 1)] : [selected];
  const baseOffset = count > 1 ? -100 : 0;

  return (
    <section className="flex flex-col items-center gap-6 bg-blossom-50 px-6 py-16 text-center">
      <p className="font-serif text-xs tracking-[0.3em] text-blossom-500">GALLERY</p>
      {count === 0 ? (
        <p className="rounded-lg border border-dashed border-blossom-200 px-6 py-12 text-sm text-ink/50">
          public/gallery 폴더에 사진을 넣고
          <br />
          lib/weddingInfo.ts의 gallery 배열에 파일명을 추가하면
          <br />이 자리에 사진이 표시됩니다.
        </p>
      ) : (
        <div className="grid w-full grid-cols-2 gap-2">
          {photos.map((file, i) => (
            <button
              key={file}
              type="button"
              onClick={() => setSelected(i)}
              aria-label={`${i + 1}번째 사진 크게 보기`}
              className="relative aspect-[3/4] overflow-hidden rounded-md bg-blossom-100"
            >
              <Image
                src={imageUrl(file, "thumb")}
                alt=""
                fill
                loading="lazy"
                sizes="(max-width: 448px) 50vw, 224px"
                className="object-cover"
              />
            </button>
          ))}
        </div>
      )}

      {selected !== null && (
        <div
          className="fixed inset-0 z-50 overflow-hidden bg-gradient-to-b from-blossom-100/95 via-white/95 to-blossom-100/95 backdrop-blur-sm"
          onClick={close}
        >
          <div
            className="flex h-full"
            style={{
              transform: `translateX(calc(${baseOffset - shift * 100}% + ${dragX}px))`,
              transition: dragging || instant ? "none" : "transform 300ms ease-out",
              touchAction: "pan-y",
            }}
            onTransitionEnd={onTransitionEnd}
            onTouchStart={onTouchStart}
            onTouchMove={onTouchMove}
            onTouchEnd={onTouchEnd}
            onTouchCancel={onTouchEnd}
          >
            {slides.map((photoIndex, slot) => (
              <div
                key={count >= 3 ? photoIndex : slot}
                className="flex h-full w-full shrink-0 items-center justify-center"
              >
                <div
                  className="relative h-[75vh] w-[calc(100%-2rem)] max-w-md overflow-hidden rounded-2xl bg-white shadow-xl"
                  onClick={(e) => e.stopPropagation()}
                >
                  <Image
                    src={imageUrl(photos[photoIndex], "full")}
                    alt=""
                    fill
                    loading="eager"
                    sizes="100vw"
                    className="object-contain"
                    draggable={false}
                  />
                </div>
              </div>
            ))}
          </div>

          <button
            type="button"
            onClick={close}
            aria-label="닫기"
            className="absolute right-4 top-4 z-10 flex h-9 w-9 items-center justify-center rounded-full bg-white text-xl leading-none text-blossom-600 shadow-md"
          >
            &times;
          </button>

          {count > 1 && (
            <>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  go(-1);
                }}
                aria-label="이전 사진"
                className="absolute left-2 top-1/2 z-10 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white text-2xl leading-none text-blossom-600 shadow-md"
              >
                &lsaquo;
              </button>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  go(1);
                }}
                aria-label="다음 사진"
                className="absolute right-2 top-1/2 z-10 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white text-2xl leading-none text-blossom-600 shadow-md"
              >
                &rsaquo;
              </button>
              <p className="absolute bottom-6 left-1/2 z-10 -translate-x-1/2 rounded-full bg-white/80 px-3 py-1 text-xs text-ink/70 shadow-sm">
                {selected + 1} / {count}
              </p>
            </>
          )}
        </div>
      )}
    </section>
  );
}
