"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";
import { weddingInfo } from "@/lib/weddingInfo";
import { SectionTitle } from "@/components/SectionTitle";
import { basePath } from "@/lib/basePath";

const SWIPE_THRESHOLD = 50;
const TAP_SLOP = 10;
const MAX_SCALE = 4;
const DOUBLE_TAP_MS = 300;
const DOUBLE_TAP_SCALE = 2.5;

type Point = { x: number; y: number };
type Zoom = { scale: number; x: number; y: number };
type Gesture =
  | { kind: "swipe"; start: Point }
  | { kind: "pan"; start: Point; startZoom: Zoom }
  | { kind: "pinch"; startDist: number; startMid: Point; startZoom: Zoom };

const NO_ZOOM: Zoom = { scale: 1, x: 0, y: 0 };

const clamp = (v: number, min: number, max: number) => Math.min(max, Math.max(min, v));
const touchPoint = (t: React.Touch): Point => ({ x: t.clientX, y: t.clientY });
const distance = (a: Point, b: Point) => Math.hypot(a.x - b.x, a.y - b.y);
const midpoint = (a: Point, b: Point): Point => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 });

// Keeps the scale in range and the zoomed photo covering its frame.
function clampZoom(z: Zoom, frame: DOMRect): Zoom {
  const scale = clamp(z.scale, 1, MAX_SCALE);
  const maxX = ((scale - 1) * frame.width) / 2;
  const maxY = ((scale - 1) * frame.height) / 2;
  return { scale, x: clamp(z.x, -maxX, maxX), y: clamp(z.y, -maxY, maxY) };
}

// Position of a screen point relative to the frame's center.
function frameOffset(p: Point, frame: DOMRect): Point {
  return { x: p.x - (frame.left + frame.width / 2), y: p.y - (frame.top + frame.height / 2) };
}

// Resized WebP variants generated by scripts/optimize-images.mjs.
function imageUrl(file: string, variant: "thumb" | "full") {
  return `${basePath}/gallery/${variant}/${file.replace(/\.[^.]+$/, "")}.webp`;
}

// Mosaic on a 3-column grid, repeating every 12 photos: a 2x2 tile on the left
// with two small ones beside it, a row of three, a 2x2 tile on the right, a row
// of three. A large tile is only used when enough photos follow to fill its rows.
function isLargeTile(i: number, count: number) {
  const remaining = count - i;
  if (i % 12 === 0) return remaining >= 3;
  if (i % 12 === 7) return remaining >= 2;
  return false;
}

export default function Gallery() {
  const photos = weddingInfo.gallery;
  const count = photos.length;

  const [selected, setSelected] = useState<number | null>(null);
  const [dragX, setDragX] = useState(0);
  const [dragging, setDragging] = useState(false);
  const [shift, setShift] = useState<-1 | 0 | 1>(0);
  const [instant, setInstant] = useState(false);
  const [zoom, setZoomState] = useState<Zoom>(NO_ZOOM);
  const zoomRef = useRef<Zoom>(NO_ZOOM);
  const frameRef = useRef<HTMLDivElement>(null);
  const gesture = useRef<Gesture | null>(null);
  const moved = useRef(false);
  const lastTap = useRef<{ time: number; point: Point } | null>(null);

  const setZoom = useCallback((z: Zoom) => {
    zoomRef.current = z;
    setZoomState(z);
  }, []);

  const wrap = useCallback((i: number) => (i + count) % count, [count]);
  const close = useCallback(() => {
    setSelected(null);
    setZoom(NO_ZOOM);
  }, [setZoom]);
  const go = useCallback(
    (dir: -1 | 1) => {
      if (count > 1) setShift((s) => (s === 0 ? dir : s));
    },
    [count],
  );

  useEffect(() => {
    if (selected === null) return;

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
      if (e.key === "ArrowLeft") go(-1);
      if (e.key === "ArrowRight") go(1);
    };
    document.addEventListener("keydown", onKeyDown);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      document.body.style.overflow = "";
    };
  }, [selected, close, go]);

  // After snapping the track back to center without animation, re-enable transitions
  // only once that position has been painted.
  useEffect(() => {
    if (!instant) return;
    const id = requestAnimationFrame(() => requestAnimationFrame(() => setInstant(false)));
    return () => cancelAnimationFrame(id);
  }, [instant]);

  const finishShift = useCallback(() => {
    if (shift === 0) return;
    setInstant(true);
    setSelected((i) => (i === null ? null : wrap(i + shift)));
    setShift(0);
    setZoom(NO_ZOOM);
  }, [shift, wrap, setZoom]);

  // transitionend never fires if the slide didn't animate (e.g. transitions were
  // off mid-gesture), which would leave the arrows locked; finish it regardless.
  useEffect(() => {
    if (shift === 0) return;
    const id = setTimeout(finishShift, 400);
    return () => clearTimeout(id);
  }, [shift, finishShift]);

  const onTransitionEnd = (e: React.TransitionEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget) finishShift();
  };

  const startPan = (start: Point) => {
    gesture.current = { kind: "pan", start, startZoom: zoomRef.current };
  };

  const onTouchStart = (e: React.TouchEvent) => {
    if (shift !== 0) return;
    setDragging(true);
    if (e.touches.length >= 2) {
      const a = touchPoint(e.touches[0]);
      const b = touchPoint(e.touches[1]);
      gesture.current = {
        kind: "pinch",
        startDist: distance(a, b),
        startMid: midpoint(a, b),
        startZoom: zoomRef.current,
      };
      moved.current = true;
      setDragX(0);
      return;
    }
    moved.current = false;
    const start = touchPoint(e.touches[0]);
    if (zoomRef.current.scale > 1) startPan(start);
    else gesture.current = { kind: "swipe", start };
  };

  const onTouchMove = (e: React.TouchEvent) => {
    const g = gesture.current;
    const rect = frameRef.current?.getBoundingClientRect();
    if (!g || !rect) return;

    if (g.kind === "pinch") {
      if (e.touches.length < 2) return;
      const a = touchPoint(e.touches[0]);
      const b = touchPoint(e.touches[1]);
      const scale = (g.startZoom.scale * distance(a, b)) / g.startDist;
      // Keep the part of the photo that started under the fingers under their midpoint.
      const start = frameOffset(g.startMid, rect);
      const mid = frameOffset(midpoint(a, b), rect);
      const px = (start.x - g.startZoom.x) / g.startZoom.scale;
      const py = (start.y - g.startZoom.y) / g.startZoom.scale;
      setZoom(clampZoom({ scale, x: mid.x - px * scale, y: mid.y - py * scale }, rect));
      return;
    }

    const p = touchPoint(e.touches[0]);
    const dx = p.x - g.start.x;
    const dy = p.y - g.start.y;
    if (Math.hypot(dx, dy) > TAP_SLOP) moved.current = true;

    if (g.kind === "pan") {
      setZoom(clampZoom({ ...g.startZoom, x: g.startZoom.x + dx, y: g.startZoom.y + dy }, rect));
    } else if (count > 1) {
      setDragX(dx);
    }
  };

  const onDoubleTap = (p: Point) => {
    const rect = frameRef.current?.getBoundingClientRect();
    if (!rect) return;
    if (zoomRef.current.scale > 1) {
      setZoom(NO_ZOOM);
      return;
    }
    const o = frameOffset(p, rect);
    const s = DOUBLE_TAP_SCALE;
    setZoom(clampZoom({ scale: s, x: o.x * (1 - s), y: o.y * (1 - s) }, rect));
  };

  const onTouchEnd = (e: React.TouchEvent) => {
    const g = gesture.current;

    // Lifting one finger of a pinch continues as a pan with the remaining one.
    if (e.touches.length > 0) {
      if (g?.kind === "pinch" && zoomRef.current.scale > 1) startPan(touchPoint(e.touches[0]));
      else gesture.current = null;
      return;
    }

    // Always clear the drag state once the last finger lifts, even if the
    // gesture was already dropped (e.g. a pinch released without zooming);
    // otherwise transitions stay off and the arrows stop working.
    gesture.current = null;
    setDragging(false);
    setDragX(0);
    if (!g) return;

    if (g.kind === "swipe") {
      if (dragX <= -SWIPE_THRESHOLD) go(1);
      else if (dragX >= SWIPE_THRESHOLD) go(-1);
    }

    const tapped = e.changedTouches[0];
    if (moved.current || !tapped || !frameRef.current?.contains(e.target as Node)) {
      lastTap.current = null;
      return;
    }
    const p = touchPoint(tapped);
    const prev = lastTap.current;
    if (prev && e.timeStamp - prev.time < DOUBLE_TAP_MS && distance(prev.point, p) < 30) {
      lastTap.current = null;
      onDoubleTap(p);
    } else {
      lastTap.current = { time: e.timeStamp, point: p };
    }
  };

  const slides =
    selected === null
      ? []
      : count > 1
        ? [wrap(selected - 1), selected, wrap(selected + 1)]
        : [selected];
  const baseOffset = count > 1 ? -100 : 0;
  const currentSlot = count > 1 ? 1 : 0;

  return (
    <section className="flex flex-col items-center gap-6 px-6 py-20 text-center">
      <SectionTitle>갤러리</SectionTitle>
      {count === 0 ? (
        <p className="rounded-lg border border-dashed border-sage-200 px-6 py-12 text-sm text-ink/50">
          public/gallery 폴더에 사진을 넣고
          <br />
          lib/weddingInfo.ts의 gallery 배열에 파일명을 추가하면
          <br />이 자리에 사진이 표시됩니다.
        </p>
      ) : (
        <div className="grid w-full grid-flow-row-dense grid-cols-3 gap-1.5">
          {photos.map((file, i) => {
            const large = isLargeTile(i, count);
            return (
              <button
                key={file}
                type="button"
                onClick={() => setSelected(i)}
                aria-label={`${i + 1}번째 사진 크게 보기`}
                className={`relative overflow-hidden rounded-sm bg-sage-100 ${
                  large ? "col-span-2 row-span-2" : "aspect-[4/5]"
                }`}
              >
                <Image
                  src={imageUrl(file, "thumb")}
                  alt=""
                  fill
                  loading="lazy"
                  sizes={large ? "(max-width: 448px) 66vw, 300px" : "(max-width: 448px) 33vw, 150px"}
                  className="object-cover"
                />
              </button>
            );
          })}
        </div>
      )}

      {selected !== null && (
        <div
          className="fixed inset-0 z-50 overflow-hidden bg-paper/95 backdrop-blur-sm"
          style={{ touchAction: "none" }}
          onClick={close}
        >
          <div
            className="flex h-full"
            style={{
              transform: `translateX(calc(${baseOffset - shift * 100}% + ${dragX}px))`,
              transition: dragging || instant ? "none" : "transform 300ms ease-out",
            }}
            onTransitionEnd={onTransitionEnd}
            onTouchStart={onTouchStart}
            onTouchMove={onTouchMove}
            onTouchEnd={onTouchEnd}
            onTouchCancel={onTouchEnd}
          >
            {slides.map((photoIndex, slot) => (
              <div
                key={count >= 3 ? photoIndex : slot}
                className="flex h-full w-full shrink-0 items-center justify-center"
              >
                <div
                  ref={slot === currentSlot ? frameRef : undefined}
                  className="relative h-[75vh] w-[calc(100%-2rem)] max-w-md overflow-hidden rounded-md bg-paper shadow-xl"
                  onClick={(e) => e.stopPropagation()}
                >
                  <div
                    className="absolute inset-0"
                    style={
                      slot === currentSlot
                        ? {
                            transform: `translate(${zoom.x}px, ${zoom.y}px) scale(${zoom.scale})`,
                            transition: dragging ? "none" : "transform 200ms ease-out",
                          }
                        : undefined
                    }
                  >
                    <Image
                      src={imageUrl(photos[photoIndex], "full")}
                      alt=""
                      fill
                      loading="eager"
                      sizes="100vw"
                      className="object-contain"
                      draggable={false}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>

          <button
            type="button"
            onClick={close}
            aria-label="닫기"
            className="absolute right-4 top-4 z-10 flex h-9 w-9 items-center justify-center rounded-full bg-white text-xl leading-none text-sage-600 shadow-md"
          >
            &times;
          </button>

          {count > 1 && (
            <>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  go(-1);
                }}
                aria-label="이전 사진"
                className="absolute left-2 top-1/2 z-10 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white text-sage-600 shadow-md"
              >
                <svg
                  viewBox="0 0 24 24"
                  className="h-5 w-5"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={2}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <path d="M15 6l-6 6 6 6" />
                </svg>
              </button>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  go(1);
                }}
                aria-label="다음 사진"
                className="absolute right-2 top-1/2 z-10 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white text-sage-600 shadow-md"
              >
                <svg
                  viewBox="0 0 24 24"
                  className="h-5 w-5"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={2}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <path d="M9 6l6 6-6 6" />
                </svg>
              </button>
              <p className="absolute bottom-6 left-1/2 z-10 -translate-x-1/2 rounded-full bg-white/80 px-3 py-1 text-xs font-normal text-ink/80 shadow-sm">
                {selected + 1} / {count}
              </p>
            </>
          )}
        </div>
      )}
    </section>
  );
}
